CREATE USER 'spring5'@'%' IDENTIFIED BY '314159265359';

CREATE DATABASE spring5fs CHARACTER SET = UTF8;

GRANT ALL PRIVILEGES ON spring5fs.* TO 'spring5'@'%';

CREATE TABLE spring5fs.MEMBER
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(100),
	NAME VARCHAR(100),
	REGDATE DATETIME,
	UNIQUE KEY (EMAIL)
) ENGINE = InnoDB CHARACTER SET = UTF8;